-- CRE AI Platform seed: 4145 Gessner, Plazas at Midtown I, Plazas at Midtown II,
-- Burlington - 10311 I-45 N, and 210 Woerner Rd.
-- Existing production schema only. Insert-only/idempotent. No credentials.
-- Detailed 23 normalized rent-roll/tenant rows are in
-- upload_4145_midtown_burlington_woerner_rent_rolls.sql.

BEGIN;

INSERT INTO properties (
 property_id,property_name,address,property_type,asking_price,noi,cap_rate,occupancy,building_sf,land_sf,year_built,broker_name,broker_email,broker_phone,source_pdf,major_risks,missing_information,estimated_arv,unit_count,opportunity_zone,value_add,extraction_confidence
)
SELECT * FROM (VALUES
 ('4145_gessner_houston_tx_2026','4145 Gessner','4145 Gessner Rd, Houston, TX 77041','Multi-Tenant Retail Center','$7,997,293','$531,820','6.65%','100%','18,228 SF including patio','1.67 AC','2023','Robert Narchi','robert.narchi@marcusmillichap.com','310-909-5426','100% Leased 6-Tenant Trophy Retail Center.pdf',jsonb_build_array('Seller credit is required for any gap between current rent and scheduled 9/1/2026 rent','Landlord remains responsible for roof and structure','Behavioral Innovations lease expires in 2031 and represents the largest suite','Tenant financial statements and sales data are not provided for all tenants'),jsonb_build_array('T12 and current collections','Executed leases and amendments','Tenant payment ledger','CAM/NNN reconciliations','Property tax and insurance backup','Roof/structure condition reports and warranties','Environmental report','Tenant financials / sales where available'),NULL::text,6,NULL::boolean,false,97),
 ('plazas_midtown_i_houston_tx_2026','Plazas at Midtown I','2501 Bagby St, Houston, TX 77006','Urban Infill Multi-Tenant Retail','$17,825,000 portfolio price for Midtown I & II; no individual allocation stated','$672,196 Year 1','Portfolio: 6.25% Month 1 annualized / 6.63% Year 1 / 6.95% stabilized','100%','15,820 SF','1.15 AC','1997 / 2021','Matt Berry','matt.berry@cbre.com','832-326-5371','Plazas at Midtown I & II.pdf',jsonb_build_array('51.1% of Midtown I NRA expires by October 2028 per rollover schedule','Stop-N-Go Gyros is at lease and seller must bridge rent if commencement has not occurred by closing','Portfolio price is not allocated between Midtown I and Midtown II','Model relies on below-market rent mark-to-market and renewal/re-leasing assumptions','Several local/regional restaurant tenants create operating and credit exposure'),jsonb_build_array('Individual property purchase-price allocation','T12 and monthly collections by property','Executed leases and amendments','Stop-N-Go executed lease and commencement evidence','Tenant sales and credit','CAM reconciliations','Tax and insurance backup','Roof warranty / 2021 replacement documentation','Environmental report'),NULL::text,NULL::integer,NULL::boolean,true,98),
 ('plazas_midtown_ii_houston_tx_2026','Plazas at Midtown II','2450 Louisiana St, Houston, TX 77006','Urban Infill Multi-Tenant Retail','$17,825,000 portfolio price for Midtown I & II; no individual allocation stated','$448,008 Month 1 annualized / $509,651 Year 1 / $563,880 Month 7 annualized','Portfolio: 6.25% Month 1 annualized / 6.63% Year 1 / 6.95% stabilized','83.6% in-place / 84% rounded; 100% stabilized with MyEyeDr. LOI','11,301 SF','0.86 AC','2001 / 2009','Matt Berry','matt.berry@cbre.com','832-326-5371','Plazas at Midtown I & II.pdf',jsonb_build_array('1,848 SF / 16.4% is not yet occupied and underwriting assumes MyEyeDr. begins May 2027','MyEyeDr. is an LOI rather than an executed in-place lease in the OM','Portfolio price is not allocated between Midtown I and Midtown II','43.8% of NRA rolls within five years per executive summary','Value creation depends on lease-up and below-market rent capture'),jsonb_build_array('Individual property purchase-price allocation','Executed MyEyeDr. lease and final commencement terms','T12 and monthly collections by property','Executed leases and amendments','Tenant sales and credit','CAM reconciliations','Tax and insurance backup','Environmental and property-condition reports'),NULL::text,NULL::integer,NULL::boolean,true,98),
 ('burlington_10311_i45_houston_tx_2026','Burlington - 10311 I-45 N','10311 I-45 N, Houston, TX 77037','Single-Tenant Net Lease Retail','$8,882,000','$577,327','6.50%','100%','30,498 SF','5.00 AC','1999 / remodeled 2005 & 2026','Matthew Mousavi','matthew.mousavi@srsre.com','949-698-1116','Burlington Houston TX.pdf',jsonb_build_array('Single-tenant concentration: 100% of income depends on Burlington','Landlord retains roof, structure and utility-line responsibilities','Year-1 tax reimbursement is capped at $4.00/SF and operating-cost reimbursement at $3.92/SF','Lease begins July 2026, so opening/commencement and rent payment should be verified'),jsonb_build_array('Executed lease and guaranty','Rent commencement/opening confirmation','Tenant estoppel','T12 / payment history after opening','Roof/structure/utility-line condition reports','Tax and insurance backup','Environmental report','Capital expenditure history for 2026 remodel'),NULL::text,1,NULL::boolean,false,98),
 ('woerner_210_houston_tx_2026','210 Woerner Rd','210 Woerner Rd, Houston, TX 77068','Commercial Land / Development Site','$1,600,000',NULL::text,NULL::text,'Vacant land / not income-producing',NULL::text,'4.23 AC',NULL::text,'Ash Noorani','ash@cbanrealestate.com','832-455-6486','Prime Hard Corner Location.pdf',jsonb_build_array('No in-place income or NOI; value depends on future development','IMST projected inside sales and fuel volume are development projections, not property income','Address is shown as both ZIP 77068 and 77090 in the flyer and must be confirmed','Entitlements, access, utility capacity, environmental condition and development costs require verification'),jsonb_build_array('Survey and legal description','Title commitment and deed restrictions','Confirmed postal address / ZIP','Phase I environmental report','Utility capacity letters','Drainage/floodplain study','Traffic/access approvals','IMST report and development plans','Geotechnical report','Development budget and entitlement status'),NULL::text,NULL::integer,NULL::boolean,true,88)
) AS v(property_id,property_name,address,property_type,asking_price,noi,cap_rate,occupancy,building_sf,land_sf,year_built,broker_name,broker_email,broker_phone,source_pdf,major_risks,missing_information,estimated_arv,unit_count,opportunity_zone,value_add,extraction_confidence)
WHERE NOT EXISTS (SELECT 1 FROM properties p WHERE p.property_id=v.property_id);

INSERT INTO documents (property_id,file_name,file_type,drive_file_id,processed_at,status)
SELECT * FROM (VALUES
 (-3581955298::bigint,'100% Leased 6-Tenant Trophy Retail Center.pdf','pdf',NULL::text,now(),'processed'),
 (-1227442445::bigint,'Plazas at Midtown I & II.pdf','pdf',NULL::text,now(),'processed'),
 (-254224862::bigint,'Plazas at Midtown I & II.pdf','pdf',NULL::text,now(),'processed'),
 (-3587931579::bigint,'Burlington Houston TX.pdf','pdf',NULL::text,now(),'processed'),
 (-4266969103::bigint,'Prime Hard Corner Location.pdf','pdf',NULL::text,now(),'processed')
) AS v(property_id,file_name,file_type,drive_file_id,processed_at,status)
WHERE NOT EXISTS (SELECT 1 FROM documents d WHERE d.property_id=v.property_id AND d.file_name=v.file_name);

INSERT INTO brokers (property_id,broker_name,broker_company,broker_email,broker_phone)
SELECT * FROM (VALUES
 (-3581955298::bigint,'Robert Narchi','Marcus & Millichap','robert.narchi@marcusmillichap.com','310-909-5426'),
 (-3581955298::bigint,'Jason Fefer','Marcus & Millichap','jason.fefer@marcusmillichap.com','310-909-2394'),
 (-3581955298::bigint,'Tyler Bindi','Marcus & Millichap','tyler.bindi@marcusmillichap.com','310-909-2374'),
 (-1227442445::bigint,'Matt Berry','CBRE','matt.berry@cbre.com','832-326-5371'),
 (-254224862::bigint,'Matt Berry','CBRE','matt.berry@cbre.com','832-326-5371'),
 (-3587931579::bigint,'Matthew Mousavi','SRS Real Estate Partners','matthew.mousavi@srsre.com','949-698-1116'),
 (-3587931579::bigint,'Patrick R. Luther, CCIM','SRS Real Estate Partners','patrick.luther@srsre.com','949-698-1115'),
 (-4266969103::bigint,'Ash Noorani','KW Commercial Texas','ash@cbanrealestate.com','832-455-6486')
) AS v(property_id,broker_name,broker_company,broker_email,broker_phone)
WHERE NOT EXISTS (SELECT 1 FROM brokers b WHERE b.property_id=v.property_id AND lower(coalesce(b.broker_name,''))=lower(coalesce(v.broker_name,'')));

INSERT INTO financial_reports (property_id,rental_income,recoveries,other_income,gross_income,taxes,insurance,cam,utilities,management_fee,total_expenses,noi,cap_rate,occupancy,source_pdf,confidence,raw_json)
SELECT * FROM (VALUES
 ('4145_gessner_houston_tx_2026','$531,820 scheduled annual rent as of 9/1/2026','NNN reimbursements; dollar amounts not stated',NULL::text,'$531,820 base rent shown; reimbursements excluded from stated amount',NULL::text,NULL::text,'Tenant NNN reimbursements; amount not stated',NULL::text,NULL::text,'Not stated; landlord limited to roof & structure','$531,820','6.65%','100%','100% Leased 6-Tenant Trophy Retail Center.pdf',97,jsonb_build_object('price',7997293,'annual_rent',531820,'noi',531820,'cap_rate_pct',6.65,'building_sf_including_patio',18228,'land_acres',1.67,'year_built',2023,'walt_years',7,'seller_credit_note','Seller will credit purchaser at closing for any difference between current rent and scheduled rent effective 9/1/2026','landlord_responsibilities',jsonb_build_array('roof','structure'),'broker_of_record',jsonb_build_object('name','Tim Speck','company','Marcus & Millichap','license','9002994'))),
 ('plazas_midtown_i_houston_tx_2026','$635,428 Year 1 potential and scheduled base rental revenue','$344,182 Year 1 reimbursement revenue','$22,611 Year 1 other revenue ($12,000 On the Kirb patio + $10,611 Dripped Birria percentage rent)','$1,002,220 Year 1 effective gross revenue','$148,470','$33,780','$117,708',NULL::text,'$30,067','$330,025','$672,196','Portfolio: 6.25% Month 1 annualized / 6.63% Year 1 / 6.95% stabilized','100%','Plazas at Midtown I & II.pdf',99,jsonb_build_object('portfolio_price',17825000,'portfolio_price_allocation','not stated','year1',jsonb_build_object('potential_base_rent',635428,'scheduled_base_rental_revenue',635428,'reimbursements',344182,'patio_rent',12000,'percentage_rent',10611,'effective_gross_revenue',1002220,'total_operating_expenses',330025,'noi',672196),'weighted_avg_rent_psf',39.33,'below_market_pct',18,'walt_years',4.4)),
 ('plazas_midtown_ii_houston_tx_2026','$487,127 Year 1 scheduled base rental revenue','$204,399 Year 1 reimbursement revenue','$32,604 Year 1 other revenue ($16,800 valet + $15,804 Dough Zone patio)','$724,130 Year 1 effective gross revenue','$105,673','$22,165','$64,917',NULL::text,'$21,724','$214,479','$448,008 Month 1 annualized / $509,651 Year 1 / $563,880 Month 7 annualized','Portfolio: 6.25% Month 1 annualized / 6.63% Year 1 / 6.95% stabilized','83.6% in-place / 100% stabilized with MyEyeDr. LOI','Plazas at Midtown I & II.pdf',99,jsonb_build_object('portfolio_price',17825000,'portfolio_price_allocation','not stated','year1',jsonb_build_object('potential_base_rent',533327,'absorption_turnover_vacancy',-46200,'scheduled_base_rental_revenue',487127,'reimbursements',204399,'valet_income',16800,'dough_zone_patio_rent',15804,'effective_gross_revenue',724130,'total_operating_expenses',214479,'noi',509651),'month1_annualized_noi',448008,'month7_annualized_noi',563880,'myeyedr_loi',jsonb_build_object('sf',1848,'assumed_start','2027-05-01','base_rent_psf',45.00))),
 ('burlington_10311_i45_houston_tx_2026','$577,327 current annual base rent','Tenant reimburses taxes, insurance and CAM; Year-1 tax reimbursement capped at $4.00/SF and operating costs at $3.92/SF',NULL::text,'$577,327 base rent plus reimbursements',NULL::text,NULL::text,'Reimbursed by tenant subject to lease caps',NULL::text,NULL::text,'Not separately stated; NN lease with roof, structure and utility-line landlord responsibilities','$577,327','6.50%','100%','Burlington Houston TX.pdf',99,jsonb_build_object('price',8882000,'noi',577327,'cap_rate_pct',6.50,'tenant','Burlington Coat Factory of Texas, L.P.','guarantor','Burlington Stores, Inc.','lease_type','NN','rentable_sf',30498,'land_acres',5.0,'lease_start','2026-07-01','lease_end','2036-06-30','current_monthly_rent',48111,'current_annual_rent',577327,'year6_monthly_rent',49458,'year6_annual_rent',593491,'year6_increase_pct',2.8,'options','4 x 5-year','reimbursement_caps',jsonb_build_object('year1_taxes_psf',4.00,'year1_operating_costs_psf',3.92,'controllable_opex_annual_cap_pct',3.0))),
 ('woerner_210_houston_tx_2026',NULL::text,NULL::text,'IMST projection: inside sales $137,727/month and fuel volume 111,784 gallons; not in-place property income',NULL::text,NULL::text,NULL::text,NULL::text,NULL::text,NULL::text,NULL::text,NULL::text,NULL::text,'Vacant land / not income-producing','Prime Hard Corner Location.pdf',90,jsonb_build_object('price',1600000,'land_acres',4.23,'price_per_sf',8.68,'zoning','Commercial','frontage_kuykendahl_ft',345,'frontage_woerner_ft',495,'utilities',jsonb_build_array('water','electricity'),'imst_projection',jsonb_build_object('inside_sales_monthly',137727,'fuel_volume_gallons',111784),'note','IMST figures are development projections and are not property NOI'))
) AS v(property_id,rental_income,recoveries,other_income,gross_income,taxes,insurance,cam,utilities,management_fee,total_expenses,noi,cap_rate,occupancy,source_pdf,confidence,raw_json)
WHERE NOT EXISTS (SELECT 1 FROM financial_reports f WHERE f.property_id=v.property_id);

INSERT INTO analysis (property_id,due_diligence_score,seller_weakness_score,acquisition_score,risk_score,upside_score,overall_score,recommendation,missing_items,weaknesses)
SELECT * FROM (VALUES
 (-3581955298::bigint,82,44,82,39,68,78,'PURSUE / VERIFY RENT COMMENCEMENT AND TENANT CREDIT. Newly built, 100% leased NNN retail with a 6.65% cap and long WALT, but buyer should verify the 9/1/2026 scheduled-rent bridge, tenant credit, and landlord roof/structure exposure.','T12 and current collections; executed leases/amendments; tenant ledger; CAM/NNN reconciliations; taxes/insurance; roof/structure reports and warranties; environmental report; tenant financials/sales.','Seller credit is needed for any current-to-9/1/2026 rent gap; landlord roof/structure responsibility; largest suite Behavioral Innovations rolls in 2031; limited tenant credit detail.'),
 (-1227442445::bigint,86,68,84,56,88,82,'PURSUE / PRICE MIDTOWN I WITH ROLLOVER DISCIPLINE. Strong 100% occupied urban-infill asset with 18% below-market rents and $672,196 Year-1 NOI, but 51.1% of NRA expires by October 2028 and the portfolio price is not allocated by property.','Individual property price allocation; T12; leases/amendments; Stop-N-Go executed lease and commencement evidence; tenant sales/credit; CAM reconciliations; taxes/insurance; roof replacement documentation; environmental report.','51.1% near-term rollover by Oct-2028; Stop-N-Go is at lease; portfolio-only pricing; restaurant/local tenant exposure; upside case depends on mark-to-market assumptions.'),
 (-254224862::bigint,84,78,86,62,94,84,'PURSUE AS VALUE-ADD / VERIFY MYEYEDR. Midtown II has strong infill fundamentals and meaningful upside, but 16.4% of the space is still represented by a MyEyeDr. LOI and Year-1 underwriting assumes future commencement.','Individual property price allocation; executed MyEyeDr. lease; final commencement and TI/LC obligations; T12; leases/amendments; tenant sales/credit; CAM reconciliations; taxes/insurance; environmental/property-condition reports.','16.4% vacancy pending MyEyeDr.; LOI is not yet an in-place lease; portfolio-only pricing; value-add depends on lease-up and below-market rent capture.'),
 (-3587931579::bigint,88,42,83,36,64,80,'PURSUE / VERIFY LEASE, GUARANTY AND CAPITAL EXPOSURE. Burlington offers a new 10-year corporate-guaranteed NN lease at a 6.50% cap, but income is 100% single-tenant and landlord retains roof, structure and utility-line responsibilities.','Executed lease and Burlington Stores guaranty; rent commencement/opening confirmation; estoppel; payment history; roof/structure/utility-line reports; tax/insurance backup; environmental report; 2026 remodel capex documentation.','Single-tenant concentration; landlord capital responsibility for roof/structure/utility lines; reimbursement caps; lease commencement is recent and should be verified.'),
 (-4266969103::bigint,55,75,62,73,88,69,'PURSUE ONLY AS DEVELOPMENT LAND / COMPLETE SITE DILIGENCE. The 4.23-acre hard-corner site has strong frontage and utility availability, but it has no in-place NOI and all value depends on entitlement, access, environmental, utility and development economics.','Survey/legal description; title/deed restrictions; confirmed ZIP/address; Phase I environmental; utility capacity; drainage/floodplain; traffic/access approvals; IMST report and plans; geotechnical report; entitlement status; full development budget.','No in-place cash flow; IMST sales/fuel figures are projections, not NOI; address ZIP inconsistency; development costs and entitlement/access risk are not established.')
) AS v(property_id,due_diligence_score,seller_weakness_score,acquisition_score,risk_score,upside_score,overall_score,recommendation,missing_items,weaknesses)
WHERE NOT EXISTS (SELECT 1 FROM analysis a WHERE a.property_id=v.property_id);

INSERT INTO committee_reports (property_id,report)
SELECT * FROM (VALUES
 ('4145_gessner_houston_tx_2026',jsonb_build_object('summary','4145 Gessner: 18,228 SF, 100% leased, $7,997,293 price, $531,820 NOI, 6.65% cap, 2023 construction.','decision','PURSUE / VERIFY RENT COMMENCEMENT AND TENANT CREDIT','broker_questions',jsonb_build_array('Send T12 and tenant ledger.','Send all leases and amendments.','Quantify seller rent bridge through 9/1/2026.','Send CAM/NNN reconciliations, taxes, insurance and roof/structure reports.'))),
 ('plazas_midtown_i_houston_tx_2026',jsonb_build_object('summary','Midtown I: 15,820 SF, 100% occupied, $672,196 Year-1 NOI, 18% below-market rent; portfolio price $17.825M is not allocated.','decision','PURSUE / PRICE MIDTOWN I WITH ROLLOVER DISCIPLINE','broker_questions',jsonb_build_array('Provide individual price allocation.','Send T12 and all leases.','Send Stop-N-Go lease/commencement status.','Provide tenant sales/credit and roof documentation.'))),
 ('plazas_midtown_ii_houston_tx_2026',jsonb_build_object('summary','Midtown II: 11,301 SF, 83.6% in-place occupancy, MyEyeDr. LOI for 1,848 SF, $509,651 Year-1 NOI.','decision','PURSUE AS VALUE-ADD / VERIFY MYEYEDR','broker_questions',jsonb_build_array('Provide individual price allocation.','Send executed MyEyeDr. lease or signed LOI.','Confirm TI/LC/free-rent obligations.','Send T12, leases, tenant credit and expense backup.'))),
 ('burlington_10311_i45_houston_tx_2026',jsonb_build_object('summary','Burlington: 30,498 SF, $8,882,000 price, $577,327 NOI, 6.50% cap, new 10-year NN lease with corporate guaranty.','decision','PURSUE / VERIFY LEASE, GUARANTY AND CAPITAL EXPOSURE','broker_questions',jsonb_build_array('Send executed lease and corporate guaranty.','Confirm rent commencement/opening.','Send estoppel/payment history and reimbursement calculations.','Provide roof/structure/utility-line reports.'))),
 ('woerner_210_houston_tx_2026',jsonb_build_object('summary','210 Woerner Rd: 4.23-acre commercial hard-corner land site at $1.6M; no in-place NOI.','decision','PURSUE ONLY AS DEVELOPMENT LAND / COMPLETE SITE DILIGENCE','broker_questions',jsonb_build_array('Confirm correct ZIP/address.','Send survey/title and full IMST report.','Confirm access and utility capacity.','Send environmental, drainage/floodplain, geotechnical and entitlement information.')))
) AS v(property_id,report)
WHERE NOT EXISTS (SELECT 1 FROM committee_reports c WHERE c.property_id=v.property_id);

INSERT INTO acquisition_decisions (property_id,decision)
SELECT * FROM (VALUES
 ('4145_gessner_houston_tx_2026',jsonb_build_object('decision','PURSUE / VERIFY RENT COMMENCEMENT AND TENANT CREDIT','next_action','Verify T12, leases, rent bridge, tenant credit and roof/structure exposure.','offer_posture','Underwrite to collectible rent at closing and documented seller credit.')),
 ('plazas_midtown_i_houston_tx_2026',jsonb_build_object('decision','PURSUE / PRICE MIDTOWN I WITH ROLLOVER DISCIPLINE','next_action','Build independent Midtown I valuation and model 2028 rollover with TI/LC/downtime.','offer_posture','Do not rely solely on portfolio cap rate or unallocated portfolio price.')),
 ('plazas_midtown_ii_houston_tx_2026',jsonb_build_object('decision','PURSUE AS VALUE-ADD / VERIFY MYEYEDR','next_action','Underwrite current and stabilized cases after verifying MyEyeDr. lease and costs.','offer_posture','Do not capitalize stabilized NOI as in-place before MyEyeDr. execution/commencement.')),
 ('burlington_10311_i45_houston_tx_2026',jsonb_build_object('decision','PURSUE / VERIFY LEASE, GUARANTY AND CAPITAL EXPOSURE','next_action','Verify lease/guaranty, commencement, payment history, reimbursements and landlord capital items.','offer_posture','Reserve for roof/structure/utility-line obligations and reimbursement leakage.')),
 ('woerner_210_houston_tx_2026',jsonb_build_object('decision','PURSUE ONLY AS DEVELOPMENT LAND / COMPLETE SITE DILIGENCE','next_action','Complete title/survey/access/utility/environmental/entitlement and development-residual work.','offer_posture','Value from verified land/development economics only; do not treat IMST projections as NOI.'))
) AS v(property_id,decision)
WHERE NOT EXISTS (SELECT 1 FROM acquisition_decisions a WHERE a.property_id=v.property_id);

COMMIT;
